from direct.actor import Actor
from direct.directnotify import DirectNotifyGlobal
from hood.folder import InteractiveAnimatedProp
from hood.folder import GenericAnimatedProp
import Globals

class TrashcanInteractiveProp(InteractiveAnimatedProp.InteractiveAnimatedProp):
    notify = DirectNotifyGlobal.directNotify.newCategory('TrashcanInteractiveProp')
    BattleCheerText = Globals.InteractivePropTrackBonusTerms[0]
    ZoneToIdles = {Globals.ToontownCentral: (('tt_a_ara_ttc_trashcan_idleTake2',
                                        1,
                                        1,
                                        None,
                                        3,
                                        10),
                                       ('tt_a_ara_ttc_trashcan_idleHiccup0',
                                        1,
                                        1,
                                        None,
                                        3,
                                        10),
                                       ('tt_a_ara_ttc_trashcan_idleLook1',
                                        1,
                                        1,
                                        None,
                                        3,
                                        10),
                                       ('tt_a_ara_ttc_trashcan_idleAwesome3',
                                        1,
                                        1,
                                        None,
                                        3,
                                        10)),
     Globals.DonaldsDock: (('tt_a_ara_dod_trashcan_idleBounce2',
                                    3,
                                    10,
                                    'tt_a_ara_dod_trashcan_idle0settle',
                                    3,
                                    10),
                                   ('tt_a_ara_dod_trashcan_idle0',
                                    1,
                                    1,
                                    None,
                                    3,
                                    10),
                                   ('tt_a_ara_dod_trashcan_idle1',
                                    1,
                                    1,
                                    None,
                                    3,
                                    10),
                                   ('tt_a_ara_dod_trashcan_idleAwesome3',
                                    1,
                                    1,
                                    None,
                                    3,
                                    10)),
     Globals.DaisyGardens: (('tt_a_ara_dga_trashcan_idleTake2',
                                     1,
                                     1,
                                     None,
                                     3,
                                     10),
                                    ('tt_a_ara_dga_trashcan_idleHiccup0',
                                     1,
                                     1,
                                     None,
                                     3,
                                     10),
                                    ('tt_a_ara_dga_trashcan_idleLook1',
                                     1,
                                     1,
                                     None,
                                     3,
                                     10),
                                    ('tt_a_ara_dga_trashcan_idleAwesome3',
                                     1,
                                     1,
                                     None,
                                     3,
                                     10)),
     Globals.MinniesMelodyland: (('tt_a_ara_mml_trashcan_idleBounce0',
                                          3,
                                          10,
                                          'tt_a_ara_mml_trashcan_idle0settle',
                                          3,
                                          10),
                                         ('tt_a_ara_mml_trashcan_idleLook1',
                                          1,
                                          1,
                                          None,
                                          3,
                                          10),
                                         ('tt_a_ara_mml_trashcan_idleHelicopter2',
                                          1,
                                          1,
                                          None,
                                          3,
                                          10),
                                         ('tt_a_ara_mml_trashcan_idleAwesome3',
                                          1,
                                          1,
                                          None,
                                          3,
                                          10)),
     Globals.TheBrrrgh: (('tt_a_ara_tbr_trashcan_idleShiver1',
                                  1,
                                  1,
                                  None,
                                  3,
                                  10),
                                 ('tt_a_ara_tbr_trashcan_idleSneeze2',
                                  1,
                                  1,
                                  None,
                                  3,
                                  10),
                                 ('tt_a_ara_tbr_trashcan_idle0',
                                  1,
                                  1,
                                  None,
                                  3,
                                  10),
                                 ('tt_a_ara_tbr_trashcan_idleAwesome3',
                                  1,
                                  1,
                                  None,
                                  3,
                                  10)),
     Globals.DonaldsDreamland: (('tt_a_ara_ddl_trashcan_idleSleep0',
                                         3,
                                         10,
                                         None,
                                         0,
                                         0),
                                        ('tt_a_ara_ddl_trashcan_idleShake2',
                                         1,
                                         1,
                                         None,
                                         0,
                                         0),
                                        ('tt_a_ara_ddl_trashcan_idleSnore1',
                                         1,
                                         1,
                                         None,
                                         0,
                                         0),
                                        ('tt_a_ara_ddl_trashcan_idleAwesome3',
                                         1,
                                         1,
                                         None,
                                         0,
                                         0))}
    ZoneToIdleIntoFightAnims = {Globals.ToontownCentral: 'tt_a_ara_ttc_trashcan_idleIntoFight',
     Globals.DonaldsDock: 'tt_a_ara_dod_trashcan_idleIntoFight',
     Globals.DaisyGardens: 'tt_a_ara_dga_trashcan_idleIntoFight',
     Globals.MinniesMelodyland: 'tt_a_ara_mml_trashcan_idleIntoFight',
     Globals.TheBrrrgh: 'tt_a_ara_tbr_trashcan_idleIntoFight',
     Globals.DonaldsDreamland: 'tt_a_ara_ddl_trashcan_idleIntoFight'}
    ZoneToVictoryAnims = {Globals.ToontownCentral: 'tt_a_ara_ttc_trashcan_victoryDance',
     Globals.DonaldsDock: 'tt_a_ara_dod_trashcan_victoryDance',
     Globals.DaisyGardens: 'tt_a_ara_dga_trashcan_victoryDance',
     Globals.MinniesMelodyland: 'tt_a_ara_mml_trashcan_victoryDance',
     Globals.TheBrrrgh: 'tt_a_ara_tbr_trashcan_victoryDance',
     Globals.DonaldsDreamland: 'tt_a_ara_ddl_trashcan_victoryDance'}
    ZoneToSadAnims = {Globals.ToontownCentral: 'tt_a_ara_ttc_trashcan_fightSad',
     Globals.DonaldsDock: 'tt_a_ara_dod_trashcan_fightSad',
     Globals.DaisyGardens: 'tt_a_ara_dga_trashcan_fightSad',
     Globals.MinniesMelodyland: 'tt_a_ara_mml_trashcan_fightSad',
     Globals.TheBrrrgh: 'tt_a_ara_tbr_trashcan_fightSad',
     Globals.DonaldsDreamland: 'tt_a_ara_ddl_trashcan_fightSad'}
    ZoneToFightAnims = {Globals.ToontownCentral: ('tt_a_ara_ttc_trashcan_fightBoost', 'tt_a_ara_ttc_trashcan_fightCheer', 'tt_a_ara_ttc_trashcan_fightIdle'),
     Globals.DonaldsDock: ('tt_a_ara_dod_trashcan_fightBoost', 'tt_a_ara_dod_trashcan_fightCheer', 'tt_a_ara_dod_trashcan_fightIdle'),
     Globals.DaisyGardens: ('tt_a_ara_dga_trashcan_fightBoost', 'tt_a_ara_dga_trashcan_fightCheer', 'tt_a_ara_dga_trashcan_fightIdle'),
     Globals.MinniesMelodyland: ('tt_a_ara_mml_trashcan_fightBoost',
                                         'tt_a_ara_mml_trashcan_fightCheer0',
                                         'tt_a_ara_mml_trashcan_fightCheer1',
                                         'tt_a_ara_mml_trashcan_fightIdle'),
     Globals.TheBrrrgh: ('tt_a_ara_tbr_trashcan_fightBoost', 'tt_a_ara_tbr_trashcan_fightCheer', 'tt_a_ara_tbr_trashcan_fightIdle'),
     Globals.DonaldsDreamland: ('tt_a_ara_ddl_trashcan_fightBoost', 'tt_a_ara_ddl_trashcan_fightCheer', 'tt_a_ara_ddl_trashcan_fightIdle')}
    IdlePauseTime = base.config.GetFloat('prop-idle-pause-time', 0.0)

    def __init__(self, node):
        InteractiveAnimatedProp.InteractiveAnimatedProp.__init__(self, node, Globals.TRASHCANS_BUFF_BATTLES)